import type { AuthorId, ConversationWindow } from "@microsonya/shared";

export interface ModelWindowMessageRole {
  readonly message: { readonly id: number };
  readonly role: "eligible" | "context";
}

export interface ModelInputPromptOptions {
  readonly includeReplyContextCapsules?: boolean;
}

export const PIPE_SEPARATOR = "|";

/** The sole ordered PIPECHAT schema. The guide and encoder derive from it. */
export const PIPE_FIELDS = [
  "#ID",
  "^PARENT",
  "AUTHOR",
  "TIME",
  "MESSAGE",
] as const;

export const PIPE_HEADER = PIPE_FIELDS.join(PIPE_SEPARATOR);

export const PIPE_GUIDE = [
  PIPE_HEADER,
  "",
  "Lines are chronological.",
  "",
  "#N identifies message N.",
  "^0 means no explicit parent.",
  "^N means the message explicitly replies to message #N.",
  "The parent message may be outside the visible window if #N is not present.",
  "",
  "AUTHOR and MESSAGE are JSON-encoded strings.",
  "AUTHOR starts with a stable window-local alias; source user IDs are hidden.",
  "TIME is normalized ISO 8601 UTC.",
  "",
  "Parent structure provides conversational context but does not by itself prove",
  "causality, agreement, contradiction, or any other semantic relation.",
  "When INPUT_ROLES is present, context-only messages resolve references only.",
  "Do not treat context-only messages as new events to classify or summarize.",
  "REPLY_CONTEXT_CAPSULES may repeat a context parent next to its eligible child",
  "to preserve reply locality. They are a derived view, not additional events.",
].join("\n");

export type ModelPolicySection = "CLASSIFICATION_POLICY" | "SUMMARY_POLICY";

export function buildModelPolicyPrompt(
  policySection: ModelPolicySection,
  policy: string,
): string {
  return `${policySection}_BEGIN\n${policy}\n${policySection}_END\n\nTRANSCRIPT_FORMAT_BEGIN\n${PIPE_GUIDE}\nTRANSCRIPT_FORMAT_END`;
}

export function buildModelInputPrompt(
  window: ConversationWindow,
  roles?: readonly ModelWindowMessageRole[],
  options: ModelInputPromptOptions = {},
): string {
  const roleSection =
    roles === undefined
      ? ""
      : `INPUT_ROLES_BEGIN\n${encodeInputRoles(roles)}\nINPUT_ROLES_END\n\n`;
  const replyCapsules =
    roles === undefined || options.includeReplyContextCapsules === false
      ? ""
      : encodeReplyContextCapsules(window, roles);
  const capsuleSection =
    replyCapsules.length === 0
      ? ""
      : `REPLY_CONTEXT_CAPSULES_BEGIN\n${replyCapsules}\nREPLY_CONTEXT_CAPSULES_END\n\n`;
  return `${roleSection}${capsuleSection}TRANSCRIPT_BEGIN\n${encodePipeWindow(window)}\nTRANSCRIPT_END`;
}

/**
 * Builds the common model envelope. Policies may differ; the format guide and
 * transcript sections are always generated by this one function.
 */
export function buildModelPrompt(
  policySection: ModelPolicySection,
  policy: string,
  window: ConversationWindow,
  roles?: readonly ModelWindowMessageRole[],
): string {
  return `${buildModelPolicyPrompt(policySection, policy)}\n\n${buildModelInputPrompt(window, roles)}`;
}

function encodeInputRoles(roles: readonly ModelWindowMessageRole[]): string {
  return roles.map(({ message, role }) => `#${message.id}|${role}`).join("\n");
}

/**
 * Co-locates an eligible reply with its context-only parent for model attention.
 * The canonical chronological transcript remains present and unchanged below.
 */
export function encodeReplyContextCapsules(
  window: ConversationWindow,
  roles: readonly ModelWindowMessageRole[],
): string {
  const roleById = new Map(
    roles.map(({ message, role }) => [message.id, role]),
  );
  const messageById = new Map(
    window.messages.map((message) => [message.id, message] as const),
  );
  const capsules: string[] = [];

  for (const child of window.messages) {
    if (roleById.get(child.id) !== "eligible" || child.parentId === null) {
      continue;
    }
    const parent = messageById.get(child.parentId);
    if (parent === undefined || roleById.get(parent.id) !== "context") continue;

    capsules.push(
      [
        `REPLY #${child.id} -> #${parent.id}`,
        `PARENT_AUTHOR ${encodePipeString(parent.author.label ?? String(parent.author.id))}`,
        `PARENT_MESSAGE ${encodePipeString(parent.text)}`,
        `CHILD_AUTHOR ${encodePipeString(child.author.label ?? String(child.author.id))}`,
        `CHILD_MESSAGE ${encodePipeString(child.text)}`,
      ].join("\n"),
    );
  }

  return capsules.join("\n\n");
}

/**
 * Encodes one immutable ConversationWindow for every model-facing consumer.
 * Author aliases are stable by first appearance and distinguish equal labels.
 */
export function encodePipeWindow(window: ConversationWindow): string {
  const { messages } = window;
  const aliases = new Map<AuthorId, string>();
  const records = new Array<string>(messages.length);

  for (let index = 0; index < messages.length; index += 1) {
    const message = messages[index]!;
    let alias = aliases.get(message.author.id);
    if (alias === undefined) {
      alias = `@${aliases.size + 1}`;
      aliases.set(message.author.id, alias);
    }
    const author = message.author.label
      ? `${alias} ${message.author.label}`
      : alias;
    records[index] =
      `#${message.id}|^${message.parentId ?? 0}|${encodePipeString(author)}|${encodePipeTime(message.time)}|${encodePipeString(message.text)}`;
  }

  return records.join("\n");
}

/** Rejects every fixed-schema PIPECHAT record violation. */
export function validatePipeRecord(record: string): void {
  const fields = record.split(PIPE_SEPARATOR);
  if (fields.length !== PIPE_FIELDS.length) {
    throw new Error(
      `Invalid PIPECHAT record: expected ${PIPE_FIELDS.length} fields, got ${fields.length}.`,
    );
  }

  const [idField, parentField, authorField, timeField, messageField] = fields;
  parsePrefixedInteger(idField!, "#", "ID", false);
  parsePrefixedInteger(parentField!, "^", "parent", true);
  parseJsonString(authorField!, "AUTHOR");
  parsePipeTime(timeField!);
  parseJsonString(messageField!, "MESSAGE");
}

function encodePipeString(value: string): string {
  const encoded = JSON.stringify(value);
  return encoded.includes(PIPE_SEPARATOR)
    ? encoded.replaceAll(PIPE_SEPARATOR, "\\u007c")
    : encoded;
}

function encodePipeTime(timestamp: number): string {
  return new Date(timestamp).toISOString().replace(".000Z", "Z");
}

function parsePrefixedInteger(
  value: string,
  prefix: string,
  label: string,
  allowsZero: boolean,
): number {
  if (!value.startsWith(prefix)) {
    throw new Error(`Invalid PIPECHAT ${label}: ${value}`);
  }

  const number = value.slice(prefix.length);
  const parsed = Number(number);
  if (!Number.isSafeInteger(parsed) || parsed < (allowsZero ? 0 : 1)) {
    throw new Error(`Invalid PIPECHAT ${label}: ${value}`);
  }
  if (String(parsed) !== number) {
    throw new Error(`Invalid PIPECHAT ${label}: ${value}`);
  }

  return parsed;
}

function parseJsonString(value: string, label: string): string {
  try {
    const parsed: unknown = JSON.parse(value);
    if (typeof parsed !== "string") throw new Error("not a string");
    return parsed;
  } catch {
    throw new Error(`Invalid PIPECHAT ${label}: expected a JSON string.`);
  }
}

function parsePipeTime(value: string): number {
  const timestamp = Date.parse(value);
  if (!Number.isFinite(timestamp) || encodePipeTime(timestamp) !== value) {
    throw new Error(`Invalid PIPECHAT TIME: ${value}`);
  }
  return timestamp;
}
