import type { ConversationWindow } from "@microsonya/shared";
import { encodePipeWindow, PIPE_GUIDE } from "./pipe.js";

export type ModelPolicySection = "CLASSIFICATION_POLICY" | "SUMMARY_POLICY";

/**
 * Builds the common model envelope. Policies may differ; the format guide and
 * transcript sections are always generated by this one function.
 */
export function buildModelPrompt(
  policySection: ModelPolicySection,
  policy: string,
  window: ConversationWindow,
): string {
  return `${policySection}_BEGIN\n${policy}\n${policySection}_END\n\nTRANSCRIPT_FORMAT_BEGIN\n${PIPE_GUIDE}\nTRANSCRIPT_FORMAT_END\n\nTRANSCRIPT_BEGIN\n${encodePipeWindow(window)}\nTRANSCRIPT_END`;
}
