import type { ConversationWindow } from "@microsonya/shared";
import { encodePipeWindow, PIPE_GUIDE } from "./pipe.js";

export type ModelPolicySection = "CLASSIFICATION_POLICY" | "SUMMARY_POLICY";

/**
 * Builds the common model envelope. Policies may differ; the format guide and
 * transcript sections are always generated by this one function.
 */
export function buildModelPrompt(
  policySection: ModelPolicySection,
  policy: string,
  window: ConversationWindow,
): string {
  return [
    promptSection(policySection, policy),
    promptSection("TRANSCRIPT_FORMAT", PIPE_GUIDE),
    promptSection("TRANSCRIPT", encodePipeWindow(window)),
  ].join("\n\n");
}

export function promptSection(name: string, content: string): string {
  return [`${name}_BEGIN`, content, `${name}_END`].join("\n");
}
