import type { ConversationWindow } from "@microsonya/shared";
import { encodePipeWindow, PIPE_GUIDE } from "./transcript.js";

export interface ModelWindowMessageRole {
  readonly message: { readonly id: number };
  readonly role: "eligible" | "context";
}

export type ModelPolicySection = "CLASSIFICATION_POLICY" | "SUMMARY_POLICY";

export function buildModelPolicyPrompt(
  policySection: ModelPolicySection,
  policy: string,
): string {
  return `${policySection}_BEGIN\n${policy}\n${policySection}_END\n\nTRANSCRIPT_FORMAT_BEGIN\n${PIPE_GUIDE}\nTRANSCRIPT_FORMAT_END`;
}

export function buildModelInputPrompt(
  window: ConversationWindow,
  roles?: readonly ModelWindowMessageRole[],
): string {
  const roleSection =
    roles === undefined
      ? ""
      : `INPUT_ROLES_BEGIN\n${encodeInputRoles(roles)}\nINPUT_ROLES_END\n\n`;
  return `${roleSection}TRANSCRIPT_BEGIN\n${encodePipeWindow(window)}\nTRANSCRIPT_END`;
}

/**
 * Builds the common model envelope. Policies may differ; the format guide and
 * transcript sections are always generated by this one function.
 */
export function buildModelPrompt(
  policySection: ModelPolicySection,
  policy: string,
  window: ConversationWindow,
  roles?: readonly ModelWindowMessageRole[],
): string {
  return `${buildModelPolicyPrompt(policySection, policy)}\n\n${buildModelInputPrompt(window, roles)}`;
}

function encodeInputRoles(roles: readonly ModelWindowMessageRole[]): string {
  return roles.map(({ message, role }) => `#${message.id}|${role}`).join("\n");
}
